# Class 10 Oct 2022
# Collection of codes generated by Umbrello

class NeuronalCell(object):

  """
   - potential: double=0.0

  :version:
  :author:
  """

  """ ATTRIBUTES

   

  MembranePotential  (private)

  """

  def computePotential(self):
    """
     

    @return double :
    @author
    """
    pass

  def did_it_fire(self):
    """
     

    @return bool :
    @author
    """
    pass

from NeuronalCell import *

class PyramidalNeuron (NeuronalCell):

  """
   

  :version:
  :author:
  """

  """ ATTRIBUTES

   

  cellOrganelle  (private)

  """

from NeuronalCell import *

class OvoidNeuron (NeuronalCell):

  """
   

  :version:
  :author:
  """

  """ ATTRIBUTES

   

  isItsMyelinated  (private)

  """


